### ISSUE TITLE
Not working with binary response?

### ISSUE THREAD

**Issue by wong2** [dempfi/ava-playback#6]
```
const test = require('ava')
const got = require('got')
const md5 = require('md5')

test('test', async t => {
  const url = 'https://httpbin.org/image/jpeg'
  const response = await got(url, { encoding: null })
  t.snapshot(md5(response.body))
})
```

```
➜  test-ava-playback AVA_PLAYBACK=record ./node_modules/.bin/ava -v

📼  [ava-playback] running in record mode
  ✔ test (1.5s)
📼  [ava-playback] new playback is recorded: /Users/wong2/tmp/test-ava-playback/playbacks/httpbin.org/get_image_jpeg-13y-hP.json

  1 test passed [19:39:10]
```

```
➜  test-ava-playback AVA_PLAYBACK=play ./node_modules/.bin/ava -v  

  ✖ test Did not match snapshot

  1 test failed [19:39:29]

  test

  /Users/wong2/tmp/test-ava-playback/test.js:9

   8:   })                            
   9:   t.snapshot(md5(response.body))
   10: })                              

  Did not match snapshot

  Difference:

  - '1842a01c84b07fb30ab4a5de686405e1'
  + 'a27095e7727c70909c910cefe16d30de'
```

**Comment by wong2** [comment]
ping @dempfi

**Comment by dempfi** [comment]
Hey @wong2 sorry to hear you had issues with this library. I’ll take a look at this issue during this weekend and will try to fix it.

**Comment by wong2** [comment]
@dempfi Thanks!

**Comment by wong2** [comment]
@dempfi any progress?

**Comment by dempfi** [comment]
This is a good one. I mean bad one, some crazy shit with encodings, still fighting with this :)

**Comment by dempfi** [comment]
ok, @wong2 this issue should be fixed in `0.0.13`

**Comment by wong2** [comment]
@dempfi Thanks! But after trying it with my example code, the problem is still there :(

```
➜  test-ava-playback AVA_PLAYBACK=play ./node_modules/.bin/ava -v  

  ✖ test Did not match snapshot

  1 test failed [19:24:34]

  test

  /Users/wong2/tmp/test-ava-playback/test.js:9

   8:   })                            
   9:   t.snapshot(md5(response.body))
   10: })                              

  Did not match snapshot

  Difference:

  - 'e8789c1feb49822b64736dc50a349de9'
  + 'a27095e7727c70909c910cefe16d30de'
```

```
➜  test-ava-playback cat node_modules/ava-playback/package.json 
{
  "_from": "ava-playback@0.0.13",
  "_id": "ava-playback@0.0.13",
```

**Comment by wong2** [comment]
:(

**Comment by dempfi** [comment]
Sorry @wong2, turns out I didn't fix general case, only for `utf8` encoding. Working on general fix now...

**Comment by dempfi** [comment]
@wong2 🎉 released new minor update with complete solution. Please check.

**Comment by wong2** [comment]
it works now, thanks!
